repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff-check
        name: "ruff: Check formatter"
        entry: ruff
        language: python
        types_or: [python, pyi, jupyter]
        args: [check, --force-exclude]
        require_serial: true
      - id: ruff-format
        name: "ruff: Format repo"
        entry: ruff
        language: python
        types_or: [python, pyi, jupyter]
        args: [format, --force-exclude]
        require_serial: true
  - repo: local
    hooks:
      - id: pylint
        name: "pylint: Python linter"
        entry: pylint
        language: python
        types: [python]
        require_serial: true
  - repo: local
    hooks:
      - id: j2lint-check
        name: "j2lint: Check formatter"
        entry: j2lint
        language: python
        files: \.(j2|jinja2|jinja)$
        args:
          - --extensions
          - j2,jinja2,jinja
          - --ignore
          - jinja-statements-delimiter
          - single-statement-per-line
          - --
        require_serial: true
